name: Greetings

on: [pull_request_target, issues,fork]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there! I noticed that this is your first issue message. Well done, stay active 💯'
        pr-message: 'Woaaah! Your first pull request. Well done, can''t wait to see your further contributions 🎉'
        fork-message: 'Hey be sure to check the issues before making a pull request 😄'